name: torrent_model
description: A Dart library for parsing .torrent file to Torrent model/saving Torrent model to .torrent file.
version: 1.0.4
repository: https://github.com/eclipseglory/torrent_model
issue_tracker: https://github.com/eclipseglory/torrent_model/issues
publish_to: https://pub.dev/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: ^3.0.3
  bencode_dart: ^1.0.3

dev_dependencies:
  test: ^1.24.3
  lints: ^2.0.1
